<a href="https://colab.research.google.com/github/lmario1999/ai2023_2_luismarioDelaa/blob/main/LeccionNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Import numpy as np and see the version
import numpy as np

In [4]:
# Create a 1D array of numbers from 0 to 9
aux=list(range(10))
print(aux)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
# Create random vector of size 10 and replace the maximum value by 0
random_vector = np.random.rand(10)

max_index = np.argmax(random_vector)

random_vector[max_index] = 0

print("Random Vector:", random_vector)

Random Vector: [0.83859517 0.30710096 0.41982255 0.09322107 0.         0.6674768
 0.12788446 0.77783213 0.46672356 0.16465276]


In [6]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

aux = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
number_8 = aux[1, 2]

print(number_8)

8


In [7]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])

aux = np.array([1, 2, 3, 4, 5, 6, 7])
numbers_345 = aux[2:5]

print(numbers_345)


[3 4 5]


In [8]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])

aux = np.array([1, 2, 3, 4, 5, 6, 7])
numeros = aux[-4:]

print(numeros)

[4 5 6 7]


In [9]:
# Create a 3×3 numpy array of all True’s

true_array = np.ones((3, 3), dtype=bool)
print(true_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [10]:
# Extract all odd numbers from arr

aux = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = aux[aux % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]


In [11]:
# Create a vector with values ranging from 10 to 49 (★☆☆)

vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# Reverse a vector (first element becomes last)

vector_np = np.array([1, 2, 3, 4, 5])

reversed_vector_np = vector_np[::-1]

print(reversed_vector_np)

[5 4 3 2 1]


In [13]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values

array = np.random.randint(0, 100, size=(10, 10))

print("Array:")
print(array)

# Find the minimum and maximum values in the array
min_value = np.min(array)
max_value = np.max(array)

print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")

Array:
[[24 93 88 52 84 87 67 60 61 43]
 [15 58 45 59 71 56 35 87 71 85]
 [14 12 76 32 46 77 97 87 78 96]
 [93  1 80 77 38 50 79 95 44 45]
 [27 83 18 47 35 15 74 59 36 80]
 [82 87 70 96 83  4 49 79 37 90]
 [90 30 14 94 88 98 52 68 90 85]
 [59 14 47 98 24 94 30 58 87 60]
 [74 60 83 70 20 52 68 16 87 14]
 [63 61 61 72 58 30 75 96 81 67]]
Minimum value: 1
Maximum value: 98


In [14]:
# Create a 3x3x3 array with random values

array_3d = np.random.rand(3, 3, 3)

print("3x3x3 Array with Random Values:")
print(array_3d)

3x3x3 Array with Random Values:
[[[0.56334097 0.31420735 0.73941232]
  [0.24415777 0.23749289 0.25841608]
  [0.38399146 0.2089733  0.94309512]]

 [[0.29128871 0.2095531  0.25066501]
  [0.89041659 0.17988225 0.79089832]
  [0.04542029 0.07906985 0.10252013]]

 [[0.06394645 0.92138658 0.61470337]
  [0.17666918 0.99673179 0.81122851]
  [0.24198399 0.90255908 0.6471947 ]]]


In [15]:
# Replace all odd numbers in arr with -1

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

mask = (arr % 2 != 0)


arr[mask] = -1

print("Array with odd numbers replaced by -1:")
print(arr)

Array with odd numbers replaced by -1:
[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [16]:
# Create an array of type float

float_array = np.array([1, 2, 3, 4], dtype=float)

print("Array of type float:")
print(float_array)

Array of type float:
[1. 2. 3. 4.]


In [17]:
# Convert a 1D array to a 2D array with 2 rows

array_1d = np.array([1, 2, 3, 4, 5, 6])

array_2d = array_1d.reshape(2, -1)  # -1 infers the number of columns

print("2D array with 2 rows:")
print(array_2d)

2D array with 2 rows:
[[1 2 3]
 [4 5 6]]


In [18]:
# How to find common values between two arrays?

Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Find common values between Z1 and Z2
common_values = np.intersect1d(Z1, Z2)

print("Common values between Z1 and Z2:")
print(common_values)

Common values between the arrays:
[3 4 5]


In [19]:
#  Consider two random array A and B, check if they are equal

# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


In [20]:
# Stack arrays a and b vertically

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

# Stack arrays a and b vertically
stacked = np.vstack((a, b))

print("Stacked arrays vertically:")
print(stacked)

Stacked arrays vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# Stack the arrays a and b horizontally.

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Stack arrays a and b horizontally
stacked = np.hstack((a, b))

print("Stacked arrays horizontally:")
print(stacked)

Stacked arrays horizontally:
[[1 2 5 6]
 [3 4 7 8]]


In [22]:
# Get all items between 5 and 10 from array tmp.

tmp = np.array([2, 4, 6, 8, 10, 12])

# Get all items between 5 and 10 from array tmp
result = tmp[(tmp >= 5) & (tmp <= 10)]

print("Items between 5 and 10 in array tmp:")
print(result)

Items between 5 and 10 in array tmp:
[ 6  8 10]


In [23]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def pair_max(a, b):
    return np.maximum(a, b)

# Example arrays a and b
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Get the pair-wise maximum of arrays a and b
result = pair_max(a, b)

print("Pair-wise maximum of arrays a and b:")
print(result)

Pair-wise maximum of arrays a and b:
[6 7 9 8 9 7 5]


In [24]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Swap columns 1 and 2 in the array arr
arr[:, [1, 2]] = arr[:, [2, 1]]

print("Array with columns 1 and 2 swapped:")
print(arr)

Array with columns 1 and 2 swapped:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [25]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

array = np.random.uniform(5, 10, size=(5, 3))

print("2D array of shape 5x3 with random decimal numbers between 5 and 10:")
print(array)

2D array of shape 5x3 with random decimal numbers between 5 and 10:
[[9.70220349 9.99294643 8.95530981]
 [8.79699141 8.93487656 9.50471799]
 [5.21308457 5.54183953 7.56968489]
 [7.81564531 8.68273512 6.42561222]
 [7.74521926 6.41163745 6.45417749]]
