<a href="https://colab.research.google.com/github/lmario1999/ai2023_2_luismarioDelaa/blob/main/TareaNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

aux=np.array([1,2,3,4,5,6,7,8])
print(aux)
print(aux.shape)

aux=np.array([[1,3,5,7],[2,4,6,8]])
print(aux.shape)
print(aux)
print(type(aux))

tmp=np.zeros(4)
print(tmp)

tmp=np.full((4,4),5)
print(tmp)

tmp=np.eye(4,4)
print(tmp)

tmp=np.ones((4,4))*3
print(tmp)

print(tmp)

[1 2 3 4 5 6 7 8]
(8,)
(2, 4)
[[1 3 5 7]
 [2 4 6 8]]
<class 'numpy.ndarray'>
[0. 0. 0. 0.]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)

[[1.56749661 7.82954523 5.30426867]
 [7.64723717 5.36450881 7.96370938]
 [7.11216709 1.27957962 0.44556623]]


In [ ]:
print(tmp[:2,:2])

[[1.56749661 7.82954523]
 [7.64723717 5.36450881]]


In [ ]:
print(tmp[:2,1:3])

[[7.82954523 5.30426867]
 [5.36450881 7.96370938]]


In [ ]:
print(tmp[1,1])

5.3645088076421015


In [ ]:
print(tmp[2,2])

0.4455662275072403


In [ ]:
mask=tmp>5
print(tmp[mask])

[7.82954523 5.30426867 7.64723717 5.36450881 7.96370938 7.11216709]


In [ ]:
mask=(tmp >=2) & (tmp <=4)
print(tmp[mask])

[]


In [ ]:
tmp=np.random.randint(0,10, size=(4,4))
print(tmp)

enteros = tmp[ tmp % 2 == 0]
print(enteros)

[[5 8 1 3]
 [5 8 7 7]
 [6 4 4 0]
 [6 6 1 9]]
[8 8 6 4 4 0 6 6]


In [ ]:
a=np.random.randint(1,11, size=(3,4))
b=np.random.randint(1,11, size=(3,4))
print(a)
print(b)

print(a.shape)
print(b.shape)

print('SUMA')
print (a+b)
print (np.add(a,b))
print('RESTA')
print (a-b)
print (np.subtract(a,b))
print('MULTIPLICACION')
print (a*b)
print (np.multiply(a,b))
print('DIVISION')
print (a/b)
print (np.divide(a,b))

[[10  2  3  8]
 [ 8  2  1 10]
 [10  7  3  8]]
[[ 2  6  5  8]
 [10 10  4  8]
 [ 8  5  7  1]]
(3, 4)
(3, 4)
SUMA
[[12  8  8 16]
 [18 12  5 18]
 [18 12 10  9]]
[[12  8  8 16]
 [18 12  5 18]
 [18 12 10  9]]
RESTA
[[ 8 -4 -2  0]
 [-2 -8 -3  2]
 [ 2  2 -4  7]]
[[ 8 -4 -2  0]
 [-2 -8 -3  2]
 [ 2  2 -4  7]]
MULTIPLICACION
[[20 12 15 64]
 [80 20  4 80]
 [80 35 21  8]]
[[20 12 15 64]
 [80 20  4 80]
 [80 35 21  8]]
DIVISION
[[5.         0.33333333 0.6        1.        ]
 [0.8        0.2        0.25       1.25      ]
 [1.25       1.4        0.42857143 8.        ]]
[[5.         0.33333333 0.6        1.        ]
 [0.8        0.2        0.25       1.25      ]
 [1.25       1.4        0.42857143 8.        ]]


In [ ]:
a=np.random.randint(1,11, size=(2,3))
b=np.random.randint(1,11, size=(3,4))
print(a)
print(b)
print(np.dot(a,b))

print('MULTIPLICACION')
print(a.dot(b))

[[ 2  5  1]
 [ 2 10  2]]
[[10  7  9  8]
 [ 3  9  5  2]
 [ 3  7  3  4]]
[[ 38  66  46  30]
 [ 56 118  74  44]]
MULTIPLICACION
[[ 38  66  46  30]
 [ 56 118  74  44]]


In [ ]:
a=np.random.randint(1,11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[ 1  3]
 [ 1 10]]
[[ 1  1]
 [ 3 10]]


In [ ]:
a=np.random.randint(1,11, size=(4,3))
b=np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(c.shape)

print(a)
print(b)
print(c)

for i in range(4):
  c[i,:]=a[i,:]+b

c=a+b
print(c)


(4, 3)
(3,)
(4, 3)
[[8 3 9]
 [8 2 1]
 [5 1 9]
 [6 8 5]]
[1 0 2]
[[10  2  3]
 [ 8  8  2]
 [ 1 10 10]
 [ 7  3  8]]
[[ 9  3 11]
 [ 9  2  3]
 [ 6  1 11]
 [ 7  8  7]]


In [ ]:
a=np.array([1,2,3])
b=np.tile(a, (6, 1))
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a=np.random.randint(0,11, size=(6,6))
print(a)
aux=np.mean(a)
print(aux)
fila=np.mean(a, axis=1)
print(fila)
columna=np.mean(a, axis=0)
print(columna)

[[ 4  3  6  3  3  9]
 [ 6  3  0  8  7  7]
 [10  9 10  0  6 10]
 [ 3  5  4  9  7  7]
 [ 0  1  6  0  1  1]
 [ 1  2  4  1 10  8]]
4.833333333333333
[4.66666667 5.16666667 7.5        5.83333333 1.5        4.33333333]
[4.         3.83333333 5.         3.5        5.66666667 7.        ]
